# Generated by Django 5.0.3 on 2025-09-17 11:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название департамента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employees.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('position', models.CharField(choices=[('junior', 'Младший специалист'), ('specialist', 'Специалист'), ('senior', 'Старший специалист'), ('lead', 'Ведущий специалист'), ('manager', 'Менеджер'), ('senior_manager', 'Старший менеджер'), ('director', 'Директор')], max_length=50, verbose_name='Должность')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Табельный номер')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department', verbose_name='Департамент')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.division', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_divisions', to='employees.employee', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee', verbose_name='Руководитель'),
        ),
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200, verbose_name='Место назначения')),
                ('start_date', models.DateField(verbose_name='Дата начала командировки')),
                ('end_date', models.DateField(verbose_name='Дата окончания командировки')),
                ('purpose', models.TextField(verbose_name='Цель командировки')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('approved', 'Одобрена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trips', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Командировка',
                'verbose_name_plural': 'Командировки',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Дата начала отпуска')),
                ('end_date', models.DateField(verbose_name='Дата окончания отпуска')),
                ('days_count', models.PositiveIntegerField(verbose_name='Количество дней')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('approved', 'Одобрен'), ('taken', 'Использован'), ('cancelled', 'Отменен')], default='planned', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Общее время работы (часы)')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_records', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись рабочего времени',
                'verbose_name_plural': 'Записи рабочего времени',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
