# Generated by Django 5.0.3 on 2025-09-18 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUDDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название устройства')),
                ('device_type', models.CharField(choices=[('turnstile', 'Турникет'), ('reader', 'Считыватель'), ('controller', 'Контроллер'), ('gate', 'Шлагбаум'), ('door', 'Дверь'), ('other', 'Другое')], max_length=20, verbose_name='Тип устройства')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('port', models.PositiveIntegerField(default=80, verbose_name='Порт')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно'), ('maintenance', 'На обслуживании'), ('error', 'Ошибка')], default='active', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Последняя связь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'СКУД устройство',
                'verbose_name_plural': 'СКУД устройства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SKUDEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, max_length=50, verbose_name='Номер карты')),
                ('event_type', models.CharField(choices=[('entry', 'Вход'), ('exit', 'Выход'), ('denied', 'Отказ в доступе'), ('alarm', 'Тревога')], max_length=20, verbose_name='Тип события')),
                ('event_time', models.DateTimeField(verbose_name='Время события')),
                ('raw_data', models.TextField(blank=True, verbose_name='Исходные данные')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='employees.skuddevice', verbose_name='Устройство')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skud_events', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Событие СКУД',
                'verbose_name_plural': 'События СКУД',
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='arrival_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records', to='employees.skudevent', verbose_name='Событие входа'),
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='departure_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_records', to='employees.skudevent', verbose_name='Событие выхода'),
        ),
    ]
