# Generated by Django 5.2.6 on 2025-09-19 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_skuddevice_skudevent_worktimerecord_arrival_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Стандартное количество рабочих часов в день', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))], verbose_name='Часов в день'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_fraction',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='1.00 = полная ставка, 0.5 = полставки, 1.5 = полтора ставки', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('2.00'))], verbose_name='Ставка работы'),
        ),
        migrations.CreateModel(
            name='WorkDaySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('first_entry', models.DateTimeField(blank=True, null=True, verbose_name='Первый вход')),
                ('last_exit', models.DateTimeField(blank=True, null=True, verbose_name='Последний выход')),
                ('total_seconds_in_office', models.PositiveIntegerField(default=0, verbose_name='Общее время в офисе (секунды)')),
                ('expected_seconds', models.PositiveIntegerField(default=0, verbose_name='Ожидаемое время работы (секунды)')),
                ('overtime_seconds', models.IntegerField(default=0, verbose_name='Переработка (секунды)')),
                ('underwork_seconds', models.IntegerField(default=0, verbose_name='Недоработка (секунды)')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Количество сессий')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('excused', 'Уважительная причина'), ('partial', 'Частично присутствовал'), ('problem', 'Проблема (нет выхода)')], default='absent', max_length=20, verbose_name='Статус дня')),
                ('has_missing_exit', models.BooleanField(default=False, verbose_name='Есть незакрытые сессии')),
                ('has_manual_corrections', models.BooleanField(default=False, verbose_name='Есть ручные корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_day_summaries', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сводка рабочего дня',
                'verbose_name_plural': 'Сводки рабочих дней',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='employees_w_employe_189c4c_idx'), models.Index(fields=['date', 'status'], name='employees_w_date_6cf003_idx'), models.Index(fields=['employee', 'date', 'status'], name='employees_w_employe_4a0624_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Автоматически рассчитывается', null=True, verbose_name='Длительность (секунды)')),
                ('status', models.CharField(choices=[('auto', 'Автоматическая'), ('manual', 'Ручная'), ('open', 'Открытая (нет выхода)'), ('closed_manual', 'Закрыта вручную')], default='auto', max_length=20, verbose_name='Статус сессии')),
                ('manual_reason', models.TextField(blank=True, verbose_name='Причина ручной корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исправил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='employees.employee', verbose_name='Сотрудник')),
                ('source_events', models.ManyToManyField(blank=True, related_name='work_sessions', to='employees.skudevent', verbose_name='Исходные события СКУД')),
            ],
            options={
                'verbose_name': 'Рабочая сессия',
                'verbose_name_plural': 'Рабочие сессии',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['employee', 'date'], name='employees_w_employe_62a18f_idx'), models.Index(fields=['employee', 'start_time'], name='employees_w_employe_09eda1_idx'), models.Index(fields=['date', 'status'], name='employees_w_date_505e89_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата изменений')),
                ('action', models.CharField(choices=[('create_session', 'Создание сессии'), ('edit_session', 'Редактирование сессии'), ('delete_session', 'Удаление сессии'), ('close_session', 'Закрытие сессии'), ('create_summary', 'Создание сводки'), ('edit_summary', 'Редактирование сводки'), ('reprocess_day', 'Пересчёт дня'), ('bulk_import', 'Массовый импорт')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание изменений')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('reason', models.TextField(verbose_name='Причина изменения')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='employees_w_employe_e95050_idx'), models.Index(fields=['changed_at'], name='employees_w_changed_93bbef_idx'), models.Index(fields=['action'], name='employees_w_action_4bb71c_idx')],
            },
        ),
    ]
