# Generated by Django 5.0.3 on 2025-09-30 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_permission_role_accesslog_rolepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pinfl',
            field=models.CharField(blank=True, help_text='14-значный персональный идентификационный номер физического лица', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='PINFL должен содержать ровно 14 цифр.', regex='^\\d{14}$')], verbose_name='PINFL'),
        ),
    ]
