# Generated by Django 5.0.3 on 2025-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_add_pinfl_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_id',
            field=models.CharField(blank=True, help_text='Идентификатор сотрудника во внешней системе СКУД', max_length=50, null=True, unique=True, verbose_name='ID в СКУД системе'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Стандартное время окончания рабочего дня (из СКУД)', null=True, verbose_name='Время окончания работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Стандартное время начала рабочего дня (из СКУД)', null=True, verbose_name='Время начала работы'),
        ),
    ]
